server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/OFFICEZIP
    driver-class-name: org.postgresql.Driver
    username: devuser
    password: devpass

  data:
    redis:
      port: 6379
      host: localhost
      password: redis@local

  jpa:
    show-sql: true
    database: postgresql
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

